CREATE DATABASE ex05;
USE ex05;
CREATE TABLE DEPARTAMENTO (
codigo INT UNSIGNED NOT NULL,
PRIMARY KEY (codigo),
descricao VARCHAR (50) NOT NULL)
ENGINE = InnoDB;
desc DEPARTAMENTO;

CREATE TABLE FUNCIONARIO (
registro INT UNSIGNED NOT NULL,
PRIMARY KEY (registro),
nome VARCHAR(80) NOT NULL,
nascimento DATE NOT NULL,
codigo INT UNSIGNED,
CONSTRAINT FK_departamento FOREIGN KEY(codigo)
references DEPARTAMENTO (codigo));

ALTER TABLE FUNCIONARIO ADD column (SALARIO DECIMAL (8,2));

DROP TABLE FUNCIONARIO;






